// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDldACx1a-IvVkM7gowpwU61TOyrpDPJ3A',
    appId: '1:585692158144:web:a6e22cb5f2d6070c8e3525',
    messagingSenderId: '585692158144',
    projectId: 'ebroker-b9384',
    authDomain: 'ebroker-b9384.firebaseapp.com',
    storageBucket: 'ebroker-b9384.appspot.com',
    measurementId: 'G-3FNTSYR41T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEUYeMdCnxnDiyMmk2CuCMyJTNZfNr7J4',
    appId: '1:585692158144:android:35f913d1a21812f58e3525',
    messagingSenderId: '585692158144',
    projectId: 'ebroker-b9384',
    storageBucket: 'ebroker-b9384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIPwyZgsZq1I-Gx4XrqPF7UuwBsd-_Ie4',
    appId: '1:585692158144:ios:03ef7ac6d8dcc9d58e3525',
    messagingSenderId: '585692158144',
    projectId: 'ebroker-b9384',
    storageBucket: 'ebroker-b9384.appspot.com',
    iosBundleId: 'com.ebroker.wrteam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIPwyZgsZq1I-Gx4XrqPF7UuwBsd-_Ie4',
    appId: '1:585692158144:ios:03ef7ac6d8dcc9d58e3525',
    messagingSenderId: '585692158144',
    projectId: 'ebroker-b9384',
    storageBucket: 'ebroker-b9384.appspot.com',
    iosBundleId: 'com.ebroker.wrteam',
  );
}
